package com.example.akremlov.nytimes.utils;

public final class Constants {
    public final static String ACTIVITY = "activity";
    public final static String SIGN_UP_ACTIVITY = "SignUpActivity";
    public final static String LANDING_ACTIVITY = "LandingActivity";
    public final static String LOG_IN_ACTIVITY = "LogInActivity";
    public final static String USERNAME = "Username";
    public final static int ARTICLES = 0;
    public final static int REFRESH_ARTICLES = 1;
    public final static String ARTICLE_BASE = "https://api.nytimes.com/svc/search/v2/articlesearch.json";
    public final static String ARTICLE_KEY = "c88d9a64ba384e4ba2a4242df4e36610";
    public final static String API_KEY = "api-key";
    public final static String FILTERRED_QUERY = "fq";
    public final static String PAGE = "page";
    public final static String SORT = "sort";
    public final static String NEWEST = "newest";
    public final static String RESPONSE = "response";
    public final static String DOCS = "docs";
    public final static String HEADLINE = "headline";
    public final static String WEB_URL = "web_url";
    public final static String SNIPPET = "snippet";
    public final static String MAIN = "main";
    public final static String MULTIMEDIA = "multimedia";
    public final static String URL = "url";
    public final static String NEW_YORK_SITE = "http://www.nytimes.com/";
    public final static String LAYOUT_MANAGER = "layoutManager";
    public final static String DATA = "data";
    public final static String PAGE_NUMBER = "page_number";
    public final static String QUERY = "query";
    public final static String PREFERENCE_FILE = "PreferenceFile";
    public final static String USER_LOGGED_IN = "USER_LOGGED_IN";
    public final static String CATEGORIES_LIST_ON_SAVE = "mCategoriesListOnSave";
    public final static String CLICKED_POSITION = "mClickedPosition";
    public static final int SELECT_PICTURE = 1;
    public static final int CAPTURE_PICTURE = 2;
    public static final int PERMISSION_REQUEST_CAMERA = 20;
    public static final int BITMAP_DIMENS = 500;
    public static final String PHOTO_FILE_PROVIDER_AUTHORITY = "com.example.akremlov.fileprovider";
    public static final String USER_IMAGE = "userImage";
}
